In [11]:
import numpy as np
import cv2
import os

In [12]:
# 加载图像并转换为矩阵
images = []
for filename in os.listdir("noise"):
    if filename.endswith(".jpg"):
        img = cv2.imread(os.path.join("noise", filename), 0)
        images.append(img)
images

[array([[ 45,   0,  50, ...,  43,  40,  88],
        [  0,  40,   1, ...,  83, 141, 100],
        [ 19,   0,  14, ...,  73,  92,  19],
        ...,
        [ 58,  52,  49, ...,  21,   0,  30],
        [ 13,  34,  65, ...,   5,  47,  65],
        [ 66,  41,  54, ...,  37,   0,   0]], dtype=uint8),
 array([[ 27,  38,   0, ...,  54,   0,  89],
        [ 13,  22,  10, ..., 111,  30,  62],
        [  0,  13,  18, ...,  20,  94, 142],
        ...,
        [ 13,  82,  50, ...,  39,  42,  13],
        [  0,  86, 100, ...,   0,  77,   0],
        [ 44,  81,   9, ...,  14,   4,  32]], dtype=uint8),
 array([[  0,   3,  71, ...,  48,  48,  94],
        [  0,   7,   0, ...,  81,  80,  88],
        [  7,   8,   9, ...,  49, 160,  22],
        ...,
        [ 24,  61,  64, ...,  11,   0,   1],
        [ 27,  11, 100, ...,   0,  18,  11],
        [  0,  55,  40, ...,  28,   2,  22]], dtype=uint8),
 array([[ 20,   0,  60, ..., 157,  32, 107],
        [ 42,   7,  26, ..., 101,  87,  71],
        [ 13,   

In [13]:
# 对所有图像矩阵进行逐元素求和
sum_matrix = np.zeros_like(images[0])
for img in images:
    sum_matrix += img

# 求取平均值矩阵
mean_matrix = sum_matrix / len(images)

# 对每个原始图像进行去噪增强
for i, img in enumerate(images):
    filtered_img = img - mean_matrix

    # 保存去噪增强后的图像
    cv2.imwrite(os.path.join("./", "filtered_img_{}.jpg".format(i)), filtered_img)
